//! Groth16 verifier helpers for per-circuit Anchor verifier programs.
//!
//! Thin wrapper over [`groth16_solana`]. Per-circuit Anchor programs hold a
//! `static` [`Groth16Vkey`] for their circuit, accept a 256-byte proof and N
//! public inputs at instruction time, and call [`verify_groth16`].
//!
//! ## Byte layout (BN254, big-endian)
//!
//! Every field element is 32 bytes BE. G1 points are `x || y` (64 B). G2
//! points are `x_c1 || x_c0 || y_c1 || y_c0` (128 B) — note the c1-first
//! ordering required by Solana's `alt_bn128` syscalls. This matches the
//! transformation in groth16-solana's canonical `parse_vk_to_rust.js`.
//!
//! ## Proof preprocessing
//!
//! Callers must pre-negate `proof.pi_a.y` (the snarkjs → Solana convention,
//! mirroring `exportSolidityCallData`). This crate does **not** touch the
//! proof bytes — keeping it allocation-free and dependency-light keeps the
//! on-chain footprint minimal.
//!
//! See `packages/vault-circuits/scripts/` for the proof-emit pipeline (added
//! in a follow-up commit).

#![no_std]

use groth16_solana::groth16::{Groth16Verifier, Groth16Verifyingkey};

/// Groth16 verifying key, formatted for groth16-solana's `alt_bn128` syscalls.
///
/// All byte arrays are big-endian. G2 limbs are `c1`-first (see module docs).
/// `ic` length is `N + 1` where `N` is the public-input count.
#[derive(Clone, Copy)]
pub struct Groth16Vkey {
    pub alpha_g1: [u8; 64],
    pub beta_g2: [u8; 128],
    pub gamma_g2: [u8; 128],
    pub delta_g2: [u8; 128],
    pub ic: &'static [[u8; 64]],
}

/// Errors surfaced by [`verify_groth16`].
///
/// The underlying `groth16-solana` crate reports a richer set of error
/// variants (e.g. malformed G1/G2 lengths, public input >= field size, syscall
/// failures). For the on-chain verifier programs we collapse all of those
/// into [`ProofInvalid`] — the caller has no useful recovery path beyond
/// rejecting the instruction, and a flat enum keeps the consuming program's
/// error mapping trivial.
///
/// [`ProofInvalid`]: VerifierError::ProofInvalid
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum VerifierError {
    #[error("public input count does not match vkey IC length")]
    SignalCountMismatch,
    #[error("groth16 proof did not verify")]
    ProofInvalid,
}

/// Verify a 256-byte Groth16 proof against a const vkey and `N` public inputs.
///
/// Proof layout: `proof[0..64] = A`, `proof[64..192] = B`, `proof[192..256] = C`.
///
/// Caller is responsible for transforming snarkjs proof bytes ahead of time:
/// `proof_a.y` must be negated; G2 limbs must be c1-first. See module docs.
pub fn verify_groth16<const N: usize>(
    vkey: &Groth16Vkey,
    proof: &[u8; 256],
    public_inputs: &[[u8; 32]; N],
) -> Result<(), VerifierError> {
    // Sanity check up-front. groth16-solana would catch this in `new(...)`
    // too, but surfacing it as a distinct variant makes the failure mode
    // explicit to callers (and cheap — it's a single integer compare).
    if vkey.ic.len() != N + 1 {
        return Err(VerifierError::SignalCountMismatch);
    }

    // groth16-solana's `Groth16Verifyingkey` borrows the IC slice and stores
    // the rest by value. We build a temporary view over our `Groth16Vkey`
    // bytes — no allocation, no copy of the IC.
    let gs_vkey = Groth16Verifyingkey {
        nr_pubinputs: N,
        vk_alpha_g1: vkey.alpha_g1,
        vk_beta_g2: vkey.beta_g2,
        // Note: the upstream struct field is misspelled `vk_gamme_g2` (sic).
        vk_gamme_g2: vkey.gamma_g2,
        vk_delta_g2: vkey.delta_g2,
        vk_ic: vkey.ic,
    };

    let proof_a: &[u8; 64] = proof[0..64].try_into().expect("64-byte slice");
    let proof_b: &[u8; 128] = proof[64..192].try_into().expect("128-byte slice");
    let proof_c: &[u8; 64] = proof[192..256].try_into().expect("64-byte slice");

    let mut verifier = Groth16Verifier::<N>::new(
        proof_a,
        proof_b,
        proof_c,
        public_inputs,
        &gs_vkey,
    )
    .map_err(|_| VerifierError::ProofInvalid)?;

    verifier.verify().map_err(|_| VerifierError::ProofInvalid)
}

#[cfg(test)]
mod tests {
    use super::*;

    // === fixture: generated by /tmp/emit-fixture.mjs (NOT committed) ===
    // circuit: aggregate_sum (N=8, claimedSum=36)
    // input: { values: [1..8], claimedSum: 36 }
    // publicSignals: ["36"]

    const ALPHA_G1: [u8; 64] = [
        27, 233, 222, 155, 234, 140, 210, 55, 231, 55, 232, 95, 26, 217, 68, 113, 224, 44, 220, 49,
        206, 231, 120, 4, 134, 170, 106, 47, 29, 102, 136, 77, 47, 43, 143, 157, 4, 224, 181, 180,
        253, 12, 249, 131, 13, 92, 210, 103, 139, 4, 132, 112, 229, 194, 174, 53, 220, 186, 210,
        36, 218, 189, 54, 54,
    ];

    const BETA_G2: [u8; 128] = [
        0, 129, 107, 63, 64, 161, 40, 177, 24, 207, 15, 64, 64, 88, 165, 148, 52, 154, 223, 78,
        130, 200, 14, 238, 83, 128, 254, 224, 196, 70, 137, 253, 31, 135, 1, 92, 238, 169, 50, 246,
        157, 150, 176, 14, 1, 66, 184, 210, 110, 18, 87, 253, 18, 55, 145, 2, 140, 76, 12, 11, 3,
        19, 55, 246, 2, 28, 235, 128, 64, 218, 161, 12, 188, 28, 149, 223, 9, 237, 36, 146, 1, 251,
        115, 2, 195, 228, 79, 232, 207, 189, 251, 42, 207, 250, 67, 108, 9, 123, 53, 85, 180, 211,
        194, 228, 17, 223, 162, 194, 25, 181, 220, 48, 26, 126, 209, 145, 51, 222, 67, 0, 73, 13,
        19, 205, 69, 84, 255, 206,
    ];

    const GAMMA_G2: [u8; 128] = [
        25, 142, 147, 147, 146, 13, 72, 58, 114, 96, 191, 183, 49, 251, 93, 37, 241, 170, 73, 51,
        53, 169, 231, 18, 151, 228, 133, 183, 174, 243, 18, 194, 24, 0, 222, 239, 18, 31, 30, 118,
        66, 106, 0, 102, 94, 92, 68, 121, 103, 67, 34, 212, 247, 94, 218, 221, 70, 222, 189, 92,
        217, 146, 246, 237, 9, 6, 137, 208, 88, 95, 240, 117, 236, 158, 153, 173, 105, 12, 51, 149,
        188, 75, 49, 51, 112, 179, 142, 243, 85, 172, 218, 220, 209, 34, 151, 91, 18, 200, 94, 165,
        219, 140, 109, 235, 74, 171, 113, 128, 141, 203, 64, 143, 227, 209, 231, 105, 12, 67, 211,
        123, 76, 230, 204, 1, 102, 250, 125, 170,
    ];

    const DELTA_G2: [u8; 128] = [
        23, 5, 206, 238, 114, 222, 4, 138, 48, 106, 241, 196, 239, 178, 244, 5, 4, 137, 102, 243,
        171, 220, 71, 28, 27, 32, 223, 65, 251, 239, 121, 118, 45, 122, 95, 193, 208, 66, 206, 163,
        231, 114, 1, 213, 117, 16, 23, 245, 169, 145, 41, 86, 52, 211, 36, 138, 199, 120, 54, 103,
        249, 15, 38, 61, 23, 48, 39, 225, 202, 55, 82, 99, 125, 150, 57, 178, 74, 110, 215, 171,
        40, 157, 4, 106, 77, 107, 213, 96, 11, 142, 79, 90, 130, 27, 235, 48, 28, 253, 205, 204,
        113, 104, 81, 17, 8, 142, 214, 195, 193, 205, 21, 166, 12, 51, 139, 122, 44, 88, 89, 241,
        36, 53, 237, 248, 138, 83, 169, 72,
    ];

    const IC: &[[u8; 64]] = &[
        [
            8, 218, 126, 118, 35, 22, 185, 242, 78, 47, 137, 8, 118, 111, 28, 151, 140, 92, 197,
            127, 228, 173, 116, 155, 155, 186, 239, 36, 11, 172, 25, 250, 10, 114, 151, 216, 32,
            228, 183, 6, 72, 112, 238, 46, 196, 74, 233, 178, 48, 126, 229, 7, 32, 2, 183, 241, 76,
            195, 224, 87, 77, 141, 27, 17,
        ],
        [
            36, 93, 27, 117, 138, 169, 153, 242, 208, 0, 52, 153, 36, 91, 188, 33, 55, 58, 107, 24,
            221, 103, 254, 98, 60, 192, 61, 175, 14, 138, 115, 234, 45, 235, 2, 82, 29, 90, 64,
            140, 70, 254, 135, 99, 54, 246, 228, 124, 229, 129, 50, 138, 64, 96, 35, 38, 62, 179,
            9, 21, 20, 190, 242, 21,
        ],
    ];

    const TEST_VKEY: Groth16Vkey = Groth16Vkey {
        alpha_g1: ALPHA_G1,
        beta_g2: BETA_G2,
        gamma_g2: GAMMA_G2,
        delta_g2: DELTA_G2,
        ic: IC,
    };

    const TEST_PROOF: [u8; 256] = [
        17, 105, 25, 32, 219, 157, 46, 224, 175, 34, 191, 83, 171, 118, 169, 167, 221, 202, 8, 115,
        114, 213, 39, 102, 183, 171, 94, 84, 156, 120, 37, 251, 40, 214, 129, 175, 151, 52, 22,
        124, 57, 74, 30, 159, 101, 29, 150, 212, 14, 111, 108, 5, 171, 219, 255, 155, 163, 158,
        128, 8, 239, 6, 187, 97, 40, 169, 101, 73, 155, 61, 186, 241, 86, 186, 201, 155, 81, 200,
        52, 175, 108, 244, 53, 59, 21, 170, 26, 171, 55, 119, 3, 79, 101, 99, 254, 74, 1, 249, 102,
        75, 24, 181, 227, 122, 236, 135, 194, 5, 175, 27, 174, 1, 122, 28, 158, 144, 245, 245, 254,
        206, 31, 85, 49, 204, 203, 104, 150, 22, 14, 2, 160, 87, 131, 82, 56, 130, 26, 109, 195,
        129, 191, 27, 151, 13, 177, 43, 251, 104, 8, 233, 245, 116, 157, 210, 122, 69, 243, 31, 42,
        42, 17, 164, 244, 252, 146, 201, 247, 69, 34, 139, 171, 52, 119, 93, 126, 159, 224, 127,
        32, 116, 36, 207, 144, 252, 190, 88, 149, 247, 191, 216, 198, 251, 5, 54, 121, 27, 60, 152,
        197, 133, 14, 238, 160, 250, 18, 252, 80, 86, 45, 238, 156, 189, 157, 117, 147, 170, 41,
        163, 75, 69, 239, 24, 150, 204, 14, 173, 141, 253, 165, 90, 126, 152, 53, 198, 232, 189,
        203, 116, 215, 124, 229, 62, 51, 28, 185, 102, 95, 120, 159, 51, 162, 148, 146, 95, 124,
        154,
    ];

    const TEST_PUBLIC_INPUTS: [[u8; 32]; 1] = [[
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 36,
    ]];

    #[test]
    fn verifies_valid_proof() {
        verify_groth16(&TEST_VKEY, &TEST_PROOF, &TEST_PUBLIC_INPUTS)
            .expect("valid proof should verify");
    }

    #[test]
    fn rejects_tampered_proof() {
        let mut bad = TEST_PROOF;
        // Flip a byte deep inside `proof_b` so we hit the pairing check, not
        // a structural validator. (Flipping in `proof_a` would still fail —
        // any bit perturbs the pairing — but using `proof_b` exercises the
        // full pairing pipeline.)
        bad[100] ^= 0x01;
        assert_eq!(
            verify_groth16(&TEST_VKEY, &bad, &TEST_PUBLIC_INPUTS),
            Err(VerifierError::ProofInvalid),
        );
    }

    #[test]
    fn rejects_wrong_public_inputs() {
        // claimedSum = 37 instead of 36.
        let wrong: [[u8; 32]; 1] = [[
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 37,
        ]];
        assert_eq!(
            verify_groth16(&TEST_VKEY, &TEST_PROOF, &wrong),
            Err(VerifierError::ProofInvalid),
        );
    }
}
