//! LiteSVM tests for the `vault_verifier_aggregate_sum` Groth16 verifier program.
//!
//! The fixture below was emitted by
//!   `packages/vault-circuits/scripts/emit-rust-vkey.mjs --circuit aggregate_sum \`
//!   `--kind fixture --inputs '{"values":[1..8],"claimedSum":36}'`
//! and matches the dev `aggregate_sum_final.zkey` baked into the program's
//! `src/vkey.rs`. Regenerate both after every trusted-setup ceremony.

use anchor_lang::InstructionData;
use solana_sdk::{
    instruction::Instruction,
    message::Message,
    signature::{Keypair, Signer},
    transaction::Transaction,
};
use stargaze_anchor_tests::{setup_verifier_svm, VAULT_VERIFIER_AGGREGATE_SUM_SO};

// === fixture: aggregate_sum (N=8, claimedSum=36) ===
// Auto-generated by packages/vault-circuits/scripts/emit-rust-vkey.mjs.
// Inputs: {"values":[1,2,3,4,5,6,7,8],"claimedSum":36}
// publicSignals: ["36"]
const TEST_PROOF: [u8; 256] = [
    15, 94, 189, 196, 250, 135, 63, 120, 66, 154, 206, 209, 207, 9, 103, 101,
    33, 52, 161, 131, 252, 55, 15, 118, 88, 245, 200, 32, 195, 190, 50, 150,
    16, 210, 197, 242, 114, 3, 184, 136, 148, 205, 10, 202, 112, 56, 91, 220,
    243, 32, 153, 101, 37, 72, 181, 220, 94, 71, 181, 69, 234, 25, 2, 75,
    23, 88, 81, 147, 128, 139, 98, 215, 168, 53, 164, 223, 105, 51, 119, 60,
    148, 153, 49, 135, 193, 144, 176, 68, 227, 129, 119, 109, 239, 9, 214, 58,
    8, 206, 79, 71, 212, 66, 102, 55, 176, 95, 142, 53, 231, 210, 227, 86,
    182, 174, 138, 114, 19, 162, 25, 229, 34, 120, 172, 29, 15, 120, 89, 181,
    14, 116, 9, 165, 156, 223, 182, 168, 208, 209, 182, 128, 221, 85, 245, 160,
    112, 135, 42, 253, 51, 109, 72, 225, 106, 92, 82, 119, 8, 229, 167, 169,
    38, 167, 201, 96, 220, 218, 132, 107, 217, 218, 52, 245, 224, 243, 16, 30,
    71, 70, 157, 189, 252, 148, 183, 165, 36, 170, 170, 119, 134, 114, 24, 221,
    19, 61, 50, 61, 93, 233, 79, 200, 101, 181, 148, 113, 38, 135, 216, 230,
    57, 19, 196, 158, 1, 140, 10, 134, 162, 177, 163, 175, 129, 92, 138, 172,
    19, 9, 229, 10, 169, 241, 227, 102, 36, 48, 138, 36, 162, 187, 149, 60,
    125, 69, 184, 248, 174, 238, 9, 107, 74, 193, 1, 57, 79, 198, 156, 136,
];

const TEST_PUBLIC_INPUT: [u8; 32] = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    36,
];

fn verify_ix(proof_bytes: [u8; 256], public_signals: Vec<[u8; 32]>) -> Instruction {
    let data = vault_verifier_aggregate_sum::instruction::Verify {
        proof_bytes,
        public_signals,
    }
    .data();
    Instruction {
        program_id: vault_verifier_aggregate_sum::ID,
        accounts: vec![],
        data,
    }
}

fn send(
    svm: &mut litesvm::LiteSVM,
    payer: &Keypair,
    ix: Instruction,
) -> Result<litesvm::types::TransactionMetadata, litesvm::types::FailedTransactionMetadata> {
    let blockhash = svm.latest_blockhash();
    let msg = Message::new(&[ix], Some(&payer.pubkey()));
    let tx = Transaction::new(&[payer], msg, blockhash);
    svm.send_transaction(tx)
}

#[test]
fn verify_accepts_valid_proof() {
    let (mut svm, payer) = setup_verifier_svm(
        vault_verifier_aggregate_sum::ID,
        VAULT_VERIFIER_AGGREGATE_SUM_SO,
    );

    let meta = send(&mut svm, &payer, verify_ix(TEST_PROOF, vec![TEST_PUBLIC_INPUT]))
        .expect("groth16 verify should succeed");

    // Surface the compute units for tuning. Look for
    // `Program <id> consumed N of M compute units` in the logs.
    for line in &meta.logs {
        if line.contains("consumed") {
            eprintln!("CU: {line}");
        }
    }
}

#[test]
fn verify_rejects_tampered_proof() {
    let (mut svm, payer) = setup_verifier_svm(
        vault_verifier_aggregate_sum::ID,
        VAULT_VERIFIER_AGGREGATE_SUM_SO,
    );

    // Flip one byte deep inside `proof_b` to force the pairing check to fail.
    let mut bad = TEST_PROOF;
    bad[100] ^= 0x01;

    let err = send(&mut svm, &payer, verify_ix(bad, vec![TEST_PUBLIC_INPUT]))
        .expect_err("tampered proof must be rejected");
    // Anchor maps `ProofInvalid` to error code 6001 (second variant in
    // `ErrorCode`). The transaction-level error is `InstructionError(0, Custom(6001))`.
    let msg = format!("{:?}", err.err);
    assert!(
        msg.contains("Custom(6001)"),
        "expected ProofInvalid (Custom(6001)), got: {msg}"
    );
}
