//! LiteSVM tests for the `vault_verifier_geofence` Groth16 verifier program.
//!
//! The fixture below was emitted by
//!   `packages/vault-circuits/scripts/emit-rust-vkey.mjs --circuit geofence \`
//!   `--kind fixture --inputs '{"lat":50,"lon":60,"minLat":40,"maxLat":70,\`
//!   `"minLon":50,"maxLon":80}'`
//! and matches the dev `geofence_final.zkey` baked into the program's
//! `src/vkey.rs`. Regenerate both after every trusted-setup ceremony.

use anchor_lang::InstructionData;
use solana_sdk::{
    instruction::Instruction,
    message::Message,
    signature::{Keypair, Signer},
    transaction::Transaction,
};
use stargaze_anchor_tests::{setup_verifier_svm, VAULT_VERIFIER_GEOFENCE_SO};

// === fixture: geofence (N=32 bit-width, 4 public signals) ===
// Auto-generated by packages/vault-circuits/scripts/emit-rust-vkey.mjs.
// Inputs: {"lat":50,"lon":60,"minLat":40,"maxLat":70,"minLon":50,"maxLon":80}
// publicSignals: ["40","70","50","80"]
const TEST_PROOF: [u8; 256] = [
    25, 117, 157, 160, 234, 43, 225, 77, 223, 168, 163, 139, 108, 212, 143, 162,
    73, 92, 90, 48, 161, 183, 204, 71, 251, 218, 133, 123, 17, 203, 221, 14,
    9, 244, 169, 49, 244, 46, 125, 68, 87, 132, 120, 172, 25, 97, 38, 131,
    18, 118, 139, 244, 49, 81, 116, 217, 83, 139, 13, 179, 114, 2, 191, 46,
    21, 124, 165, 129, 161, 123, 60, 21, 5, 160, 14, 209, 22, 12, 228, 177,
    150, 66, 30, 225, 136, 154, 234, 50, 111, 112, 93, 59, 36, 133, 209, 242,
    6, 253, 255, 164, 120, 183, 172, 71, 59, 167, 108, 20, 118, 182, 188, 72,
    239, 234, 188, 115, 152, 155, 188, 158, 71, 243, 238, 89, 187, 254, 75, 233,
    24, 58, 107, 113, 19, 102, 108, 249, 131, 234, 188, 243, 32, 63, 99, 29,
    93, 37, 48, 141, 244, 179, 227, 154, 107, 48, 42, 7, 206, 233, 33, 185,
    18, 193, 240, 174, 245, 152, 92, 166, 135, 14, 176, 232, 111, 137, 130, 14,
    207, 99, 43, 199, 1, 118, 201, 244, 165, 11, 115, 128, 92, 45, 224, 62,
    26, 200, 60, 211, 232, 254, 233, 118, 97, 149, 134, 188, 174, 133, 217, 192,
    5, 213, 233, 143, 190, 244, 85, 198, 74, 95, 68, 93, 130, 141, 39, 14,
    42, 88, 6, 174, 207, 141, 137, 218, 156, 136, 66, 174, 52, 234, 104, 48,
    234, 124, 119, 62, 62, 248, 97, 146, 24, 167, 9, 93, 210, 157, 38, 135,
];

const TEST_PUBLIC_INPUTS: [[u8; 32]; 4] = [
    [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40,
    ],
    [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 70,
    ],
    [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50,
    ],
    [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80,
    ],
];

fn verify_ix(proof_bytes: [u8; 256], public_signals: Vec<[u8; 32]>) -> Instruction {
    let data = vault_verifier_geofence::instruction::Verify {
        proof_bytes,
        public_signals,
    }
    .data();
    Instruction {
        program_id: vault_verifier_geofence::ID,
        accounts: vec![],
        data,
    }
}

fn send(
    svm: &mut litesvm::LiteSVM,
    payer: &Keypair,
    ix: Instruction,
) -> Result<litesvm::types::TransactionMetadata, litesvm::types::FailedTransactionMetadata> {
    let blockhash = svm.latest_blockhash();
    let msg = Message::new(&[ix], Some(&payer.pubkey()));
    let tx = Transaction::new(&[payer], msg, blockhash);
    svm.send_transaction(tx)
}

#[test]
fn verify_accepts_valid_proof() {
    let (mut svm, payer) = setup_verifier_svm(
        vault_verifier_geofence::ID,
        VAULT_VERIFIER_GEOFENCE_SO,
    );

    let meta = send(
        &mut svm,
        &payer,
        verify_ix(TEST_PROOF, TEST_PUBLIC_INPUTS.to_vec()),
    )
    .expect("groth16 verify should succeed");

    // Surface the compute units for tuning. Look for
    // `Program <id> consumed N of M compute units` in the logs.
    for line in &meta.logs {
        if line.contains("consumed") {
            eprintln!("CU: {line}");
        }
    }
}

#[test]
fn verify_rejects_tampered_proof() {
    let (mut svm, payer) = setup_verifier_svm(
        vault_verifier_geofence::ID,
        VAULT_VERIFIER_GEOFENCE_SO,
    );

    // Flip one byte deep inside `proof_b` to force the pairing check to fail.
    let mut bad = TEST_PROOF;
    bad[100] ^= 0x01;

    let err = send(
        &mut svm,
        &payer,
        verify_ix(bad, TEST_PUBLIC_INPUTS.to_vec()),
    )
    .expect_err("tampered proof must be rejected");
    // Anchor maps `ProofInvalid` to error code 6001 (second variant in
    // `ErrorCode`). The transaction-level error is `InstructionError(0, Custom(6001))`.
    let msg = format!("{:?}", err.err);
    assert!(
        msg.contains("Custom(6001)"),
        "expected ProofInvalid (Custom(6001)), got: {msg}"
    );
}
